---
title: "**CAPSTONE PROJECT** <br/> A World Tour in Data"
date: "`r Sys.Date()`"
output: 
  rmdformats::material:
    code_folding: hide
css: custom.css
bibliography: References.bib  
csl: https://www.zotero.org/styles/stavebni-obzor
---

---
nocite: '@*'
---

```{=html}
<style>
.html-widget {
    margin: auto;
}
</style>
```
```{r setup, include=FALSE}

# Global options

knitr::opts_chunk$set(cache = TRUE, warning = FALSE, comment = FALSE, message = FALSE)

rm(list = ls())
```

# **Libraries**

```{r class.source = "fold-show"}

library(rmdformats)
library(data.table)
library(devtools)
library(kableExtra)
library(tidyverse)
library(esquisse)
library(countrycode)
library(leaflet)
library(leaflet.extras)
library(leaflet.extras2)
library(sf)
library(htmltools)
library(RColorBrewer)
library(DT)
library(shiny)


```

```{r}
# Functions

addLegend_decreasing <- function (map, position = c("topright", "bottomright", "bottomleft","topleft"),
                                  pal, values, na.label = "NA", bins = 7, colors, 
                                  opacity = 0.5, labels = NULL, labFormat = labelFormat(), 
                                  title = NULL, className = "info legend", layerId = NULL, 
                                  group = NULL, data = getMapData(map), decreasing = FALSE) {
  
        position <- match.arg(position)
        type <- "unknown"
        na.color <- NULL
        extra <- NULL
        if (!missing(pal)) {
            if (!missing(colors)) 
                stop("You must provide either 'pal' or 'colors' (not both)")
            if (missing(title) && inherits(values, "formula")) 
                title <- deparse(values[[2]])
            values <- evalFormula(values, data)
            type <- attr(pal, "colorType", exact = TRUE)
            args <- attr(pal, "colorArgs", exact = TRUE)
            na.color <- args$na.color
            if (!is.null(na.color) && col2rgb(na.color, alpha = TRUE)[[4]] == 
                    0) {
                na.color <- NULL
            }
            if (type != "numeric" && !missing(bins)) 
                warning("'bins' is ignored because the palette type is not numeric")
            if (type == "numeric") {
                cuts <- if (length(bins) == 1) 
                    pretty(values, bins)
                else bins   
                if (length(bins) > 2) 
                    if (!all(abs(diff(bins, differences = 2)) <= 
                                     sqrt(.Machine$double.eps))) 
                        stop("The vector of breaks 'bins' must be equally spaced")
                n <- length(cuts)
                r <- range(values, na.rm = TRUE)
                cuts <- cuts[cuts >= r[1] & cuts <= r[2]]
                n <- length(cuts)
                p <- (cuts - r[1])/(r[2] - r[1])
                extra <- list(p_1 = p[1], p_n = p[n])
                p <- c("", paste0(100 * p, "%"), "")
                if (decreasing == TRUE){
                    colors <- pal(rev(c(r[1], cuts, r[2])))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }else{
                    colors <- pal(c(r[1], cuts, r[2]))
                    labels <- rev(labFormat(type = "numeric", cuts))
                }
                colors <- paste(colors, p, sep = " ", collapse = ", ")
            }
            else if (type == "bin") {
                cuts <- args$bins
                n <- length(cuts)
                mids <- (cuts[-1] + cuts[-n])/2
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "bin", cuts))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "bin", cuts)
                }
            }
            else if (type == "quantile") {
                p <- args$probs
                n <- length(p)
                cuts <- quantile(values, probs = p, na.rm = TRUE)
                mids <- quantile(values, probs = (p[-1] + p[-n])/2, na.rm = TRUE)
                if (decreasing == TRUE){
                    colors <- pal(rev(mids))
                    labels <- rev(labFormat(type = "quantile", cuts, p))
                }else{
                    colors <- pal(mids)
                    labels <- labFormat(type = "quantile", cuts, p)
                }
            }
            else if (type == "factor") {
                v <- sort(unique(na.omit(values)))
                colors <- pal(v)
                labels <- labFormat(type = "factor", v)
                if (decreasing == TRUE){
                    colors <- pal(rev(v))
                    labels <- rev(labFormat(type = "factor", v))
                }else{
                    colors <- pal(v)
                    labels <- labFormat(type = "factor", v)
                }
            }
            else stop("Palette function not supported")
            if (!any(is.na(values))) 
                na.color <- NULL
        }
        else {
            if (length(colors) != length(labels)) 
                stop("'colors' and 'labels' must be of the same length")
        }
        legend <- list(colors = I(unname(colors)), labels = I(unname(labels)), 
                                     na_color = na.color, na_label = na.label, opacity = opacity, 
                                     position = position, type = type, title = title, extra = extra, 
                                     layerId = layerId, className = className, group = group)
        invokeMethod(map, data, "addLegend", legend)
        }

```

# **Data**

```{r results='hide'}

# Life Expectancy

DATA_LE_1 <- fread("DATA/Life Expectancy/1.annual-death-rate-by-age-group_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_2 <- fread("DATA/Life Expectancy/2.healthy-life-expectancy-and-years-lived-with-disabilityhealthy-life-expectancy-vs-health-expenditure-per-capita_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_3 <- fread("DATA/Life Expectancy/3.healthy-life-expectancy-vs-health-expenditure-per-capita_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_4 <- fread("DATA/Life Expectancy/4.life-expectancy-marimekko_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_5 <- fread("DATA/Life Expectancy/5.world-life-expectancy_from_ourworldindata-org_24.02.2024.csv")

# Loneliness

DATA_LO_1 <- fread("DATA/Loneliness/1.one-person-households_from_ourworldindata-org_24.02.2025.csv")

DATA_LO_2 <- fread("DATA/Loneliness/2.one-person-households-vs-gdp-per-capita_from_ourworldindata-org_25.02.2024.csv")

DATA_LO_3 <- fread("DATA/Loneliness/3.people-who-report-having-friends-or-relatives-they-can-count-on_from_ourworldindata-org_24.02.2024.csv")

DATA_LO_4 <- fread("DATA/Loneliness/4.self-reported-loneliness-older-adults_from_ourworldindata-org_24.02.2024.csv")

# GEO COUNTRIES

geojson <- sf::st_read("DATA/Map/countries.geojson")


```

```{r}

head(DATA_LE_5) %>%
  kbl() %>%
  kable_styling()

head(DATA_LO_1) %>%
  kbl() %>%
  kable_styling()

```

# **Visuals**

## One Person Household and Life Expectancy in The World (Between 1960 and 2018)

```{r out.width="99%"}

# DATA ETL ----------

TEMP <- merge(DATA_LE_5, DATA_LO_1, by = c("Code", "Year"))

TEMP <- TEMP %>% select(-c("Entity.x"))

TEMP <- na.omit(TEMP)

TEMP <- na.omit(TEMP[!apply(TEMP[, c("Code")], 1, function(x) any(is.na(x) | x == "")), ])

value_counts <- table(TEMP$Code)

TEMP <- TEMP[!(TEMP$Code %in% names(value_counts[value_counts <= 2])), ]

TEMP <- TEMP %>%
  group_by(Code) %>%
  mutate(Correlation=cor(`Period life expectancy at birth - Sex: all - Age: 0`, `Share of one person households`)) %>% ungroup()

TEMP <- TEMP %>%
  rename(Country = Entity.y)

TEMP <- TEMP %>%
  group_by(Code, Country, Correlation) %>%
  summarise(Year_Count= n_distinct(Year))

TEMP1 <- geojson %>%
  right_join(TEMP, by = c("ISO_A3" = "Code"))

remove(TEMP)

# DATA MAPPING ---------

TEMP1 <- na.omit(TEMP1)

TEMP1$Correlation <- round(TEMP1$Correlation,3)

TEMP1 <- TEMP1 %>% select(-Country)

# LEAFLEET MAPPING ---------

# Title
title <- tags$div(
   HTML("One Person Household and Life Expectancy in The World", "<br/>", "Between 1960 and 2018")
 )  

# Tooltip
mytext <- paste(
   "<b>", TEMP1$ADMIN, "</b><br/>",
    "Correlation: ",TEMP1$Correlation,"<br/>", 
    "Year Used: ",TEMP1$Year_Count,"<br/>", 
    sep="") %>%
  lapply(htmltools::HTML)

# Color Palette
pal <- colorNumeric(palette = "RdBu", domain = c(-1,1))

map <- leaflet(TEMP1) %>%
  addTiles() %>% 
  setView(lat=35, lng=-12 , zoom=1.5) %>%
  addPolygons(
    fillColor = ~pal(Correlation),
    fillOpacity = 0.9,
    color = "white",
    stroke = TRUE,
    weight = 0.3,
    smoothFactor = 0.8,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto")
  ) %>% addProviderTiles("CartoDB.PositronNoLabels") %>%
  addLegend(
    position = "bottomleft",
    pal = pal,
    values = c(-1,1),
    title = "Correlation",
    opacity = 1
  ) %>%
    addFullscreenControl()

# Display Map
map

```

```{r}

# Full Cleaning

rm(list = ls())

```

```{r}

# Select Year

Year_Filter <- 2018
```

## One Person Household Share Around The World

```{r out.width="99%"}

# DATA ETL ----------

TEMP <- na.omit(DATA_LO_1)

# DATA MAPPING ---------

TEMP1 <- geojson %>%
  right_join(TEMP, by = c("ISO_A3" = "Code"))

TEMP1 <- na.omit(TEMP1)

# YEAR FILTERING --------------

TEMP1 <- filter(TEMP1,TEMP1$Year == "2010")

# ROUNDING ---------------

TEMP1$`Share of one person households` <- round(TEMP1$`Share of one person households`,2)

# LEAFLEET MAPPING ----------------

# Title
title <- tags$div(
   HTML("One Person Household Around The World", "<br/>", "Between 1960 and 2018")
 )  

# Tooltip
mytext <- paste(
   "<b>", TEMP1$ADMIN, "</b><br/>",
    "One Person Households","<br/>"," ","<br/>","Share: ",TEMP1$`Share of one person households`,"%",
    sep="") %>%
  lapply(htmltools::HTML)

# Color Palette
pal <- colorNumeric(palette = "Blues", domain = c(0,max(TEMP1$`Share of one person households`)), reverse = FALSE)

map <- leaflet(TEMP1) %>%
  addTiles() %>% 
  setView(lat=35, lng=-12 , zoom=1.5) %>%
  addPolygons(
    fillColor = ~pal(TEMP1$`Share of one person households`),
    fillOpacity = 0.9,
    color = "white",
    stroke = TRUE,
    weight = 0.3,
    smoothFactor = 0.8,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto")
  ) %>% addProviderTiles("CartoDB.PositronNoLabels") %>% 
addLegend_decreasing('bottomleft', pal = pal, values = c(0,max(TEMP1$`Share of one person households`)), title = "Share %", decreasing = TRUE, opacity = 1) %>% addFullscreenControl()

# Display Map -------------------------------
map

```

```{r}

# Full Cleaning

rm(list = ls())

```

# **References**
