---
title: "CAPSTONE PROJECT <br/> A World Tour in Data"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: true
    toc_depth: 3
    number_sections: false
    code_folding: hide
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE, warning = FALSE, comment = FALSE, message = FALSE, echo = FALSE)
```

# LIBRARIES

```{r class.source = 'fold-show'}

library(devtools)
library(data.table)
library(tidyverse)
library(esquisse)
library(countrycode)
library(leaflet)
library(sf)
library(htmltools)
library(RColorBrewer)

```

# DATA

```{r class.source = 'fold-show'}

# Life Expectancy

DATA_LE_1 <- fread("DATA/Life Expectancy/1.annual-death-rate-by-age-group_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_2 <- fread("DATA/Life Expectancy/2.healthy-life-expectancy-and-years-lived-with-disabilityhealthy-life-expectancy-vs-health-expenditure-per-capita_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_3 <- fread("DATA/Life Expectancy/3.healthy-life-expectancy-vs-health-expenditure-per-capita_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_4 <- fread("DATA/Life Expectancy/4.life-expectancy-marimekko_from_ourworldindata-org_24.02.2024.csv")

DATA_LE_5 <- fread("DATA/Life Expectancy/5.world-life-expectancy_from_ourworldindata-org_24.02.2024.csv")

# Loneliness

DATA_LO_1 <- fread("DATA/Loneliness/1.one-person-households_from_ourworldindata-org_24.02.2025.csv")

DATA_LO_2 <- fread("DATA/Loneliness/2.one-person-households-vs-gdp-per-capita_from_ourworldindata-org_25.02.2024.csv")

DATA_LO_3 <- fread("DATA/Loneliness/3.people-who-report-having-friends-or-relatives-they-can-count-on_from_ourworldindata-org_24.02.2024.csv")

DATA_LO_4 <- fread("DATA/Loneliness/4.self-reported-loneliness-older-adults_from_ourworldindata-org_24.02.2024.csv")

# GEO COUNTRIES

geojson <- sf::st_read("DATA/Map/countries.geojson")


```

# VISUALS

```{r}

TEMP <- merge(DATA_LE_5, DATA_LO_1, by = c("Code", "Year"))

TEMP <- TEMP %>% select(-c("Entity.x"))

TEMP <- na.omit(TEMP)

TEMP <- na.omit(TEMP[!apply(TEMP[, c("Code")], 1, function(x) any(is.na(x) | x == "")), ])

value_counts <- table(TEMP$Code)

TEMP <- TEMP[!(TEMP$Code %in% names(value_counts[value_counts <= 2])), ]

TEMP <- TEMP %>%
  group_by(Code) %>%
  mutate(Correlation=cor(`Period life expectancy at birth - Sex: all - Age: 0`, `Share of one person households`)) %>% ungroup()

TEMP <- TEMP %>%
  rename(Country = Entity.y)

TEMP <- TEMP %>%
  group_by(Code, Country, Correlation) %>%
  summarise(Year_Count= n_distinct(Year))

TEMP1 <- geojson %>%
  left_join(TEMP, by = c("ISO_A3" = "Code"))

remove(TEMP)

TEMP1 <- na.omit(TEMP1)

TEMP1$Correlation <- round(TEMP1$Correlation,4)

TEMP1 <- TEMP1 %>% select(-Country)

```

## One Person Household and Life Expectancy

```{r, fig.width=12}

# Tooltip
mytext <- paste(
   "<b>", TEMP1$ADMIN, "</b><br/>",
    "Correlation: ",TEMP1$Correlation,"<br/>", 
    "Year Used: ",TEMP1$Year_Count,"<br/>", 
    sep="") %>%
  lapply(htmltools::HTML)

# Color Palette
pal <- colorNumeric(palette = "RdBu", domain = c(-1,1))

map <- leaflet(TEMP1) %>%
  addTiles() %>% 
  setView(lat=35, lng=15.2551 , zoom=1.45) %>%
  addPolygons(
    fillColor = ~pal(Correlation),
    fillOpacity = 0.9,
    color = "white",
    stroke = TRUE,
    weight = 0.3,
    smoothFactor = 0.8,
    label = mytext,
    labelOptions = labelOptions( 
      style = list("font-weight" = "normal", padding = "3px 8px"), 
      textsize = "13px", 
      direction = "auto")
  ) %>% addProviderTiles("CartoDB.PositronNoLabels") %>% 
  addLegend(
    position = "bottomleft",
    pal = pal,
    values = c(-1,1),
    title = "Correlation",
    opacity = 1
  )

# Display Map
map

```

```{r}
remove(TMP1)
```
